executor: slurm
# rerun-incomplete: True
jobs: 64
printshellcmds: True
max-jobs-per-second: 1
restart-times: 3
latency-wait: 60

default-resources:
  c: 1
  runtime: 720
  nodes: 1
  slurm_partition: "12hours"

groups:
  download_file: download
group-components:
  download: 8
